apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: workshop
  name: rimi-docker-lurkbook
  labels:
    app: rimi-docker-lurkbook

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: rimi-docker-lurkbook

  template:
    metadata:
      labels:
        app: rimi-docker-lurkbook
      annotations:
    spec:
      containers:
        - image: gcr.io/unity-ads-workshop-test/rimi-docker-lurkbook:master
          name: rimi-docker-lurkbook
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 0.5
              memory: 1024Mi
          env:
            - name: SOME_ENV_VARIABLE
              value: some env value

      nodeSelector:
        cloud.google.com/gke-nodepool: workshop-pool
