kind: Service
apiVersion: v1
metadata:
  labels:
    app: rimi-docker-lurkbook
  name: rimi-docker-lurkbook
  namespace: workshop

spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: rimi-docker-lurkbook
